### ISSUE TITLE
Build failure when handling MkDocs skeleton repositories

### ISSUE THREAD

**Issue by stuartmccoll** [LandRegistry/common-dev-env#45]
* **I'm submitting a ...**

  * [X] feature request (possible bug report, depending on whether this is something that was previously considered)

* **What is the current behavior?**
The development environment fails to build when searching for `configuration.yml` for repositories based on the [mkdocs](https://www.mkdocs.org) skeleton.

```
No configuration.yml found for documentation
Searching for NGINX conf files in the apps
No configuration.yml found for documentation
Searching for Elasticsearch initialisation scripts in the apps
No configuration.yml found for documentation
Searching for elasticsearch5 initialisation scripts in the apps
No configuration.yml found for documentation
logic.rb:261:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
```

* **If the current behavior is a bug, what are the steps to reproduce?**
Include a repository based on the [mkdocs](https://www.mkdocs.org) skeleton and attempt to run a fresh `source run.sh up`.

* **What is the expected/proposed behavior?**
To be discussed - should teams include these as part of their dev-env-config, or should we be running these separately? If including them, should the development environment handle running the skeleton, or should it skip over the repository and leave it to devs to run locally?

* **What is the motivation / use case for changing the behavior?**
  Including local copies of documentation repositories which use the [mkdocs](https://www.mkdocs.org) skeleton.

* **Please tell us about your environment:**

  * Common-dev-env version: `v1.1.0`
  * Operating system (and shell, if not the OS default): macOS
  * Ruby version: `2.2.3p173`

**Comment by sdchapman** [comment]
Not having a configuration.yml isn't a fatal error, and not having a compose fragment should just mean no  image is built or container is created - in other words, the clone is the only thing that happens. Your Mkdocs repository could add those files to make it into a runnable thing if desired. The skeleton it's based on never considered running in the dev-env, but it's a good idea.

The logic.rb error you are seeing is because you appear to be on Ruby 2.2, but Ruby 2.3 is the minimum requirement for the common-dev-env. If you install [rbenv](https://github.com/rbenv/rbenv#installation) and use it to [install](https://github.com/rbenv/rbenv#installing-ruby-versions) a newer ruby version, then your dev-env should at least complete the up process.
